#!/bin/sh

OUT=./bundled_openapi.yaml

openapi-spec-cli --spec-path ./reference/openapi.yaml --bundled-spec-path $OUT

if [ -d ./docs/api ]; then
  rm -r ./docs/api
fi

mkdir -p ./docs/api
redoc-cli bundle $OUT
mv redoc-static.html ./docs/api/index.html
