#!/bin/sh

OUT=./.output/bundled_openapi.yaml

openapi-spec-cli --spec-path ./reference/openapi.yaml --bundled-spec-path $OUT
openapi-redoc-schema-def --path $OUT --tags model_component model_request model_response

mkdir -p ./docs/api
redoc-cli bundle $OUT -o ./docs/api/index.html
