components:
  schemas:
    MeGetResponse:
      $ref: '#/components/schemas/User'
      x-tags:
      - model_response
    User:
      properties:
        id:
          example: 1
          type: integer
        name:
          example: John Doe
          type: string
      required:
      - id
      - name
      title: User
      type: object
      x-tags:
      - model_component
  securitySchemes:
    ApiToken:
      description: "```\nHeaders:\n  Authorization: \"Bearer <token>\"\n```"
      scheme: bearer
      type: http
info:
  description: null
  title: API Sample
  version: '1.0'
openapi: 3.0.0
paths:
  /me:
    get:
      description: ''
      operationId: get-me
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeGetResponse'
          description: OK
      security:
      - ApiToken: []
      summary: "\u8A8D\u8A3C\u30E6\u30FC\u30B6\u30FC\u60C5\u5831"
      tags:
      - api_app
servers:
- description: Local
  url: http://localhost:3000
tags:
- description: ''
  name: api_app
  x-displayName: API for app
- description: '## User

    <SchemaDefinition schemaRef="#/components/schemas/User" />

    '
  name: model_component
  x-displayName: Component Models
- description: ''
  name: model_request
  x-displayName: Request Models
- description: '## MeGetResponse

    <SchemaDefinition schemaRef="#/components/schemas/MeGetResponse" />

    '
  name: model_response
  x-displayName: Response Models
x-tagGroups:
- name: APIs
  tags:
  - api_app
- name: Models
  tags:
  - model_component
  - model_request
  - model_response
