openapi: 3.0.0
info:
  title: API Sample
  version: '1.0'
  description: ''
  contact:
    url: 'https://github.com/dforest/openapi-redoc-boilerplate'
servers:
  - url: 'http://localhost:3000'
    description: Local
tags:
  - name: api_app
    x-displayName: API for app
    description: null
  - name: model_component
    x-displayName: Component Models
    description: null
  - name: model_request
    x-displayName: Request Models
    description: null
  - name: model_response
    x-displayName: Response Models
    description: null
x-tagGroups:
  - name: APIs
    tags:
      - api_app
  - name: Models
    tags:
      - model_component
      - model_request
      - model_response
paths:
  /me:
    get:
      summary: My user information
      tags:
        - api_app
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeGetResponse'
      operationId: get-me
      description: ''
      security:
        - ApiToken: []
components:
  schemas:
    MeGetResponse:
      type: object
      properties:
        user:
          $ref: './schemas.yaml#/components/schemas/User'
      x-tags:
        - model_response
  securitySchemes:
    ApiToken:
      type: http
      scheme: bearer
      description: |-
        ```
        Headers:
          Authorization: "Bearer <token>"
        ```
