openapi: 3.0.0
info:
  title: schemas
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
      required:
        - id
        - name
      x-tags:
        - model_component
